### ISSUE TITLE
Crear una plantilla para el correo de aceptación e instalación

### ISSUE THREAD

**Issue by ccordoba12** [PythonBootcampUniandes/instalacion#2]
@andfoy, puedes crear por fa en este repo una plantilla con el correo de aceptación e instalación?

No te olvides de mencionar que vamos a estar en Starbucks el Jueves de 5 a 8 pm para resolver dudas de instalación, que el curso arranca a las 9 am, y que en caso de que no puedan ir el Jueves, vamos a resolver dudas el Sábado entre 8:30 y 9:00. Pero que en ningún caso vamos a resolver estas dudas durante el curso.

@forero, algo más que debamos mencionar?

**Comment by forero** [comment]
Hay algo que creo que es obvio pero nunca mencionamos y deberiamos hacerlo ahora: que esperamos que cada persona traiga su laptop.
